site_name: tracker solaire 
pages:
- 'Présentation.md'
- 'Partie_mécanique.md'
- 'Partie_electronique.md'
- 'Partie_logiciel.md'
- 'Courbe_du_soleil.md'
- 'Historique_année_précédent.md'
- 'Modification_tuto.md'
- 'etat_avancement.md'
theme: readthedocs 
